### ISSUE TITLE
Support for Elasticsearch 7.17.2

### ISSUE THREAD

**Issue by santala** [EvidentSolutions/elasticsearch-analysis-raudikko#3]
From the README:

> The plugin should support all 7.x.x versions, but Elasticsearch requires the plugin to declare an exact ES version, so each release of the plugin has several packages per ES version. Check [releases](https://github.com/EvidentSolutions/elasticsearch-analysis-raudikko/releases) if the version you need is included, and if not, please create an issue requesting support for that version.

This issue is to request support for Elasticsearch 7.17.2.

Currently, all 7.17.x versions are missing from build output.

**Comment by hakuzumon** [comment]
Thanks for the request, I added 7.17.2 package to the asset list of v0.1.1.
